### ISSUE TITLE
txt detect as application/octet-stream

### ISSUE THREAD

**Issue by MrSwed** [gabriel-vasile/mimetype#336] opened 2022-10-21 06:15 UTC
Example txt [txt.txt](https://github.com/gabriel-vasile/mimetype/files/9836186/txt.txt) detect as `application/octet-stream`

**Comment by gabriel-vasile** [comment] 2022-11-01 17:31
I tested your file using the latest release of `mimetype` and it is correctly detected as `text/plain`.

**Comment by MrSwed** [comment] 2022-11-01 20:01
very strange, how can i achieve this?  

the latest release is 1.4.1.

the result is the same:
<details><summary>Details, click to open</summary>

![image](https://user-images.githubusercontent.com/5120610/199326494-dc02b99f-ed2a-4a35-bc65-3a3775ad8440.png)

</details>

**Comment by gabriel-vasile** [comment] 2022-11-01 20:16
Oh, I see. The problem appears when you call `mimetype.SetLimit(1024*1024)` before detection. Let me see what's the problem and how to fix it.

**Comment by gabriel-vasile** [comment] 2022-11-02 10:34
The problem is the test file contains the `0x0B` (vertical tab) character at index 4478.

Computer files can be either binary files or text files. 
`mimetype` uses the [MIME sniffing standard](https://mimesniff.spec.whatwg.org/) to detect text files. 
This standard says: _If the [resource header](https://mimesniff.spec.whatwg.org/#resource-header) contains no [binary data bytes](https://mimesniff.spec.whatwg.org/#binary-data-byte), the [computed MIME type](https://mimesniff.spec.whatwg.org/#computed-mime-type) is "text/plain"._

`0x0B` is considered binary data byte in this standard so the file is not detected as `text/plain`.


If you want these types of files to be detected as `text/plain` you can [extend mimetype to detect other formats](https://pkg.go.dev/github.com/gabriel-vasile/mimetype#example-package-Extend).

**Comment by gabriel-vasile** [comment] 2022-11-02 10:39
There are different approaches to what is considered a text file.
One is the MIME sniffing standard I linked above.
The Linux `file` utility for example, considers text files any file that does not contain the null `0x00` byte. For this reason, `file` detects your file as `text/plain`.
![image](https://user-images.githubusercontent.com/10602896/199468898-688d2937-42f6-4902-a7b5-519a69bfd85b.png)

**Comment by zdiff** [comment] 2024-05-22 23:44
Do you think it would benefit this project to allow users to choose the binary file detection method: MIME sniffing standard or the looser Linux file standard?

**Comment by gabriel-vasile** [comment] 2024-10-24 14:36
> Do you think it would benefit this project to allow users to choose the binary file detection method: MIME sniffing standard or the looser Linux file standard?

I think users would be confused if mimetype did this kind of separation.
I will close this. If you need it, then use [Extend](https://pkg.go.dev/github.com/gabriel-vasile/mimetype#example-package-Extend).

**Closed by gabriel-vasile** 2024-10-24 14:36 UTC
