### ISSUE TITLE
.xsl file type is being detected as application/msword

### ISSUE THREAD

**Issue by InfoLibre** [gabriel-vasile/mimetype#230] opened 2021-12-28 17:03 UTC
**Attach the file for which the detection is inaccurate**
You can use the file sharing site of your choice, just ensure the file will not expire or get deleted.

[Bibliothèque de macros pour extraire des données de Baan.xls.zip](https://github.com/gabriel-vasile/mimetype/files/7785686/Bibliotheque.de.macros.pour.extraire.des.donnees.de.Baan.xls.zip)

(unzip it to test)

**Expected MIME type**

application/vnd.ms-excel ?

**Returned MIME type**

application/msword

**Version of the library you are using**

1.4.0

**Output of `go version`**

go version go1.13.8 linux/amd64

**Additional context**

I'm using this code:

[add_media.go.zip](https://github.com/gabriel-vasile/mimetype/files/7785693/add_media.go.zip)

**Comment by gabriel-vasile** [comment] 2022-01-10 21:17
`mimetype` looks only at the [first few bytes](https://github.com/gabriel-vasile/mimetype/blob/db2464c28aec4d6b0bf14bebba595b1ca4061d75/mimetype.go#L16-L17) and sometimes the .xls signature is at the end of the file.
Try increasing readLimit:
```go
// increase to 1MB, default is 3KB.
mimetype.SetLimit(1024 * 1024)
mimetype.DetectFile("file.xls")
```

**Comment by gabriel-vasile** [comment] 2024-01-26 16:20
I can confirm the issue is fixed for the attached file when increasing `ReadLimit`:
```go
mimetype.SetLimit(1024 * 1024)
```
so let me close this issue.

**Closed by gabriel-vasile** 2024-01-26 16:20 UTC
